### ISSUE TITLE
Compiler requirement specification

### ISSUE THREAD

**Issue by LiamBindle** [GEOS-ESM/MAPL#109]
Hi everyone,

Have MAPL's compiler requirements been formalized? I seem to recall GCC >= 8 and Intel >= 18 being mentioned in the past&mdash;is that correct? What compilers and compiler versions does GMAO test MAPL with? Do you know of any definite minimum requirements (e.g. it definitely won't compile with GCC 7)?

Thanks in advance!

Liam

**Comment by tclune** [comment]
Liam,

Any specific answer to such a question is tentative at best.      Currently we test with gfortran 8.2 and ifort 18.0.5  (I think, but @mathomp4 would need to confirm).      And while we don't purposefully do anything to force ourselves onto more recent compilers, we will often jump to a new version if it solves a problem for us.  But when we do, there is a great deal of testing.

For the moment, we cannot install ifort 19 on most nodes of discover, so our upgrade path is quite limited for the moment.    E.g.,  last week we implemented a workaround for a memory leak exposed in ifort 18 but was not present in ifort 19.    If we could have upgraded to 19 that might have been the more expedient solution.   

For MAPL itself, I think we should try harder to maintain compiler version support than for GEOS.   This is because people are using it with older versions of GEOS and we now have 2 external orgs that use MAPL.         In that respect, I would commit to ensuring support for the latest patch of each recent version of GCC and ifort.     E.g., that would mean support for GCC 8.3 without guarantees for 8.2 and ifort 18.0.5 without guarantees for ifort 18.0.3.

So then the question becomes: "Does MAPL work with  GCC 7, GCC 8, GCC9, ifort 17, ifort 18, and ifort 19?"     The answer is probably, but we only test with 2 of those and only a small fraction of the code is currently covered by unit tests.    In practice this would instead mean that if someone finds a problem under, say, GCC 7,  we would consider finding a workaround a high-priority.

With MAPL-2 being released real soon,  I will drop GCC 7 and ifort 17. From the list and add GCC10 which should be out very soon now.

How's that for a fence-sitting answer?  :-)

**Comment by LiamBindle** [comment]
@tclune 
Thanks, this is just what I was looking for! I figured there wasn't a formal specification, but knowing you guys are thinking the latest GCC 8 and Intel 18 minors is good to know.

Thanks!

Liam
