### ISSUE TITLE
Hanging in HIST on AWS when too many output variables are asked for

### ISSUE THREAD

**Issue by LiamBindle** [GEOS-ESM/MAPL#1184]
Hi all,

Last week I did some testing of GCHP on AWS, and I narrowed in on the specifics of the one outstanding issue I'm aware of. In general, GCHP runs well on AWS using Parallel Cluster, and there isn't really anything "special" you need to do. I successfully tested full chemistry simulations up to C180 resolution on up to 1044 physical cores, and the only issue I ran into is freezing/hanging/crashing in `HISTORY` at write-time if I asked for too many output variables. 

## Problem Description
In general, if you ask for too many output variables it hangs indefinitely during "writing X slices to file Y". The threshold isn't perfectly consistent, but the table below is a pretty good approximation 

| # nodes | C90 resolution | C180 resolution |
|:---:|:---:|:---:|
| 5 | ~70 variables | *not tested* |
| 10 | ~25 variables | ~130 variables |
| 20 | ~25 variables | ~100 variables |

These thresholds are the number of variables I could put in HISTORY before my simulations started to hang. I was able to reproduce these thresholds 2-3 times each. I ran these tests with a single collection, but I did found that multiple smaller collections didn't change the total number of variables before HISTORY would hang.

The general trend is:
- Increasing resolution --> more output variables are possible
- Increasing core-count --> fewer output variables are possible

When I killed the simulations I often saw `MPI_Win_Fence` near the top of the stack trace. 

### Other info I found (but nothing important)
- These thresholds were consistent with FSx for Lustre (AWS's version of Lustre) or EBS file systems. I found that multinode simulations with EFS would crash, but those crashes were related to reading data (not important because FSx for Lustre and EBS are what we want anyways).
- All my tests used Amazon's EFA fabric, Intel OneAPI 2021.4, and Intel MPI 2019 Update 10, and MAPL 2.6.3.

## Next Steps?

What are the possible culprits here? I'm happy to do some more information gathering if you can point me in a direction.

If it's useful, I could share SSH access to my Parallel Cluster instance and you could log in and tries things for yourself.

**Comment by mathomp4** [comment]
@LiamBindle Do you know how many IOserver nodes you were running? I know @weiyuan-jiang has some rules-of-thumb we coded into `gcm_run.j` that set the number of backend PEs for the multigroup server based on the number of collections and number of IO nodes:

https://github.com/GEOS-ESM/GEOSgcm_App/blob/78cd9bd85c4f2e6cddc6754e1f391bca5d373c54/gcm_run.j#L784-L803

Though maybe @weiyuan-jiang has better recommendations now?

**Comment by LiamBindle** [comment]
@mathomp4 Are "IOserver nodes" the same as the dedicated nodes for the output server? If so, I'm not using any. If it isn't the same thing, then I'm using whatever our default is (I can check what that is if you can point me to where it's configured).

**Comment by mathomp4** [comment]
Oh. Hmm. yeah, I mean extra nodes. I'm not sure we've tried 130 C180 HISTORY outputs without IOserver!

**Comment by LiamBindle** [comment]
@mathomp4 Ah, good to know! Honest question: is that a crazy thing to do? I don't have any intuition for what's reasonable here.

**Comment by mathomp4** [comment]
> @mathomp4 Ah, good to know! Honest question: is that a crazy thing to do? I don't have any intuition for what's reasonable here.

@LiamBindle I'm not sure. I think we usually run with a couple IO nodes at C180+ just so we can do some async history and I suppose dedicate the compute nodes to computation. Maybe @bena-nasa or @weiyuan-jiang have more experience?

You might want to try the multigroup server with a couple IO nodes and see if it helps. I suppose it's more expensive because more EC2 nodes, but that's better than not running!

**Comment by atrayano** [comment]
@LiamBindle Considering the general trend, this looks like an MPI issue to me. I have absolutely no experience with AWS, but I am wondering if it is possible to try a deferent MPI implementation (is there such a thing?). In the past (more that 5 years ago) we had  bad experience with one-sided MPI communication pretty much with every available MPI implementation on discover. Since then the situation has improved, but since you are seeing that most cores are waiting at MPI_Win_Fence and we are using one-sided communication in our IO server, make me believe that another MPI implementation might behave better. Of course, trying Matt's suggestion to use dedicated IO nodes might help too (but then the issue might be related to memory)

**Comment by mathomp4** [comment]
@LiamBindle Another question: How up-to-date are your "Baselibs". I know @tclune and @weiyuan-jiang did fix up some MPI window issues both in GFE libraries and in MAPL. (MAPL 2.6.3 is a bit old so maybe a fix came in in between? Not sure. I haven't done an AWS run in a while.)

**Comment by tclune** [comment]
@atrayano We only use the one-sided during the initial handshake between the model and the server.  After that it is just good old-fashioned ISEND/IRECV.  The description indicates that the failure is a bit later in the process.   Is it possible that ISEND/IRECV indirectly call some of the FENCE routines?

**Comment by weiyuan-jiang** [comment]
Please try multi group oserver. Can you post you gcm_run.j script here?

**Comment by tclune** [comment]
@weiyuan-jiang This is not GCM.  There is no `gcm_run.j` script.

**Comment by tclune** [comment]
@LiamBindle - I'm wondering if I should spin someone on my team to be able to build and run GCHP in our environment?  Even if we can't reproduce problems, it will improve our ability to articulate what to change for things like O-Server and such.   Could even provide us with another test before MAPL releases.  (Not that we'd let old GCHP get in the way of new MAPL, so that may not be useful at this time.)

**Comment by LiamBindle** [comment]
Hi all, thanks for the replies. I'm happy to try some more things, but because it works okay for < ~30 output variables, that covers most scientific applicaitons, so I'm trying to avoid getting too bogged down in this.

I agree it seems like an MPI issue. Note that this **only happens on AWS**; we frequently use several hundred output variables on other clusters.

In terms of next steps, the suggestions are
- Try a different MPI
- Try o-server

I'm happy to try both, but I wanted to confirm that these are worth exploring because they aren't trivial (this work is ~10% of my time). If the culprit is likely one-sided communication, do you think one-sided OSU benchmarks would be worth running?

**Comment by mathomp4** [comment]
@LiamBindle I guess another question is what instances are you running on? Are you on EFA enabled ones like C5n.18xlarge?

**Comment by LiamBindle** [comment]
@mathomp4 That's right. C5n.18xlarge with EFA enabled and FSx for Lustre.
