### ISSUE TITLE
Non-fatal error in MAPL_Generic.F90 when required restart file doesn't exist

### ISSUE THREAD

**Issue by LiamBindle** [GEOS-ESM/MAPL#1312]
Hi all,

I'm upgrading MAPL in GCHP to 2.16 and I'm running into an issue with our timers. The stack trace I'm trying to troubleshoot is

```
pe=00004 FAIL at line=00167    BaseProfiler.F90                         <Timer <GCHP> does not match start timer <GCHPchem>>
pe=00004 FAIL at line=01814    MAPL_Generic.F90                         <status=1>
pe=00004 FAIL at line=00616    MAPL_CapGridComp.F90                     <status=1>
pe=00004 FAIL at line=00918    MAPL_CapGridComp.F90                     <status=1>
pe=00004 FAIL at line=00259    MAPL_Cap.F90                             <status=1>
pe=00004 FAIL at line=00218    MAPL_Cap.F90                             <status=1>
pe=00004 FAIL at line=00152    MAPL_Cap.F90                             <status=1>
pe=00004 FAIL at line=00129    MAPL_Cap.F90                             <status=1>
pe=00004 FAIL at line=00031    GCHPctm.F90                              <status=1>
```

To me, it looks like a `MAPL_TimerOff('GCHP', ...)` is being called after a `MAPL_TimerOn('GCHPchem', ...)`. Note that this happens immediately after launching (in INITIALIZE).

I'm going to dig deeper, but I figured I'd post an issue here in case someone has a suggestions---is there anything new with the new MAPL timers that could be related? I'll keep looking.

Thanks!

**Comment by tclune** [comment]
So far these types of issues have always proven to be a bug in the client code.   You need to find why TimerOff was not called for `GCHPchem`.   Usually this is because of some failure (`rc /= 0`) that was not trapped at some higher level. So instead of the code aborting you end up continuing on but with the timers in an inconsistent state.

Hope that helps.

**Comment by LiamBindle** [comment]
Thanks Tom. I was just about to post an update. 

It looks like there was a non-fatal error higher up that I didn't notice. Specifically here: https://github.com/GEOS-ESM/MAPL/blob/779c94be75980f36f0bb05f74d18d81070b03407/generic/MAPL_Generic.F90#L5931 (a required restart file doesn't exist). The restart file is present though (`+initial_GEOSChem_rst.c24_fullchem.nc`). Looking into this now. Any insight you have would be greatly appreciated.

**Comment by LiamBindle** [comment]
It looks like the `inquire` [here](https://github.com/GEOS-ESM/MAPL/blob/779c94be75980f36f0bb05f74d18d81070b03407/generic/MAPL_Generic.F90#L5896) is being called with the `+` prefix included. Is that expected? Looking deeper.

**Comment by LiamBindle** [comment]
Oh, I see the changelog for 2.12.0 says support for the +/- options for restart names was removed. Is there an alternative option?

**Comment by bena-nasa** [comment]
What's the problem, your rc file still has a + in front of the restart name? If so can't you just remove the + in the rc file?

**Comment by LiamBindle** [comment]
I can remove the `+` in which case it read the file okay, but our restart files are missing a couple variables. IIUC the old behaviour is missing variables were initialized to zero right? Is there a similar option?

**Comment by bena-nasa** [comment]
@LiamBindle when the variables are allocated they are set to 0 (unless you have a different default value in the addvarspec call). This does not depend on whether or not the variable is in the file since you have to allocate memory for the field before it can be read. So if you removed the + and it didn't die or throw errors I think you are fine. I'm not sure this "old behaviour" you are talking about it.
I also can't tell you exactly what the +/- actually even did anymore in all cases, I'm pretty sure they were mostly bandaids for problems with binary files since you have no idea what was in them, even I was confused by these +/- options...

**Comment by LiamBindle** [comment]
@bena-nasa Thanks for the info. I ended up adding explicit zero variables to our restart files. I think requiring that the restart files cover all of the internal state variables is reasonable.

Thanks for your guys help! Looking forward to using these updates!
