### ISSUE TITLE
Is there a way to avoid these broadcast calls?

### ISSUE THREAD

**Issue by wmputman** [GEOS-ESM/MAPL#1382]
https://github.com/GEOS-ESM/MAPL/blob/0dbe0f14adf059e53d29112d0ee2da9f4d560275/base/MAPL_sun_uc.F90#L2748-L2753

Can we do some kind of parallel read here instead of having the root node broadcast everything.  This is trapping a load imbalance from the moist physics leading to a significant overhead in Surface times.

Every PE is opening and closing the file currently as it is written

**Comment by wmputman** [comment]
Also, does this have to happen every tilmestep??? It seems like it is. It probably needs to happen just once per simulated day, on the frequency of the daily data in the file

**Comment by dr0cloud** [comment]
Hi @wmputman , I am taking a look and also pinging @mathomp4 who had a major role in the development of this part of the solar source code. Peter.

**Comment by tclune** [comment]
Coming at this cold:
1. The 3 Bcasts can certainly be turned into a single bcast with 3 items.  But this is only useful if the call is frequent.
2. If what @dr0cloud says is correct, then should not the open/read not only be on the root process but also only during init rather than using a `TableCreated` flag?

**Comment by mathomp4** [comment]
@wmputman I can see how to optimize this a bit. I talked with @dr0cloud and we can make it better.
