### ISSUE TITLE
Add support for diurnal mean history output

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1537]
Recently, @acollow emailed OTRS about an issue with archiving in experiments, etc. But, one thing she mentioned was that she wanted to produce "diurnal monthly means". I was a bit unsure what that meant, so she helped me out:

> The diurnal monthly mean gets generated as part of the post processing routine and is a monthly
> mean for each hour of the day (or in my case every 3 hours). These files, along with the monthly
> means are still getting generated. My experiment home directory is
> /discover/nobackup/acollow/SEA_EMIP_Control/ and an example diurnal monthly mean can be found in
> /discover/nobackup/acollow/SEA_EMIP_Control/geosgcm_prog/diurnal. It is the same thing as the
> tavgU collections from MERRA-2.

I'm guessing this is something @lltakacs (?) added to `time_ave.x` long ago. But now that MAPL can provide monthly collections directly via History, perhaps MAPL could do the same for diurnal collections? 

I suppose now the question for @acollow (and perhaps @sdrabenh) is "What should this be and look like?" For example I can think of a couple things (assuming @bena-nasa, @atrayano or @tclune say this is possible):

1. @acollow already mentions that there could be a 1-hourly or 3-hourly average. This leads to how "generic" should this capability be? I mean, in History1G I can see maybe supporting hour-level averaging, but maybe in yaml-based History2G (which might use ISO 8601) maybe we could support any divisible time-increment? Though maybe that's overkill? 🤷🏼 
2. How should MAPL *name* these files. Monthly is simple, but should these be `diurnal_1hr` or go full ISO 8601 as `diurnal_PT1H` in case we start supporting more generic intervals?

**Comment by bena-nasa** [comment]
@mathomp4 certainly doable, my only concern is that History is getting a bit spaghetti codish at this point, worried this will just make that worse. And things get complicated, now when we checkpoint the collection if we are in the middle of the month, if you want the diurnal every hour that is either 24 checkpoints per collection or a big checkpoint..., what is you stop on the 1st of the month, you only need to checkpoint part of the day. There is a non-trivial amount of machinery to invent here I think, even with what @atrayano has already done for the monthlies.

**Comment by tclune** [comment]
This is somewhat related to another recent request (forgot who) for a file that shows fields at "local noon".

**Comment by sdrabenh** [comment]
If there is consideration on enhancing MAPL's monthly logic, I would first request that all checkpoint files are written in netcdf instead of binary. I agree with @bena-nasa that the logic will get complicated by dropping checkpoints in the middle of a month for diurnal output. This might require the addition of some internal counters in the checkpoint files. If an option for diurnal output is pursued, would it also be possible to output the field variances (if user specified) in the monthly output? @lltakacs averaging did this for most/all collections. Variances are needed for the plots package for certain collections (prog, iau, etc), and right now I have to output daily files in order to generate the require variances.

**Comment by tclune** [comment]
@lltakacs  Isn't the method you suggest much more expensive?     A proper diurnal mean would have 24 arrays (per field) written each month, whereas an hourly output (with post processing) would require 24*30 arrays (per field) to be written out?    Meanwhile that I/O is slowing down other people's I/O as well.

**Comment by acollow** [comment]
I agree that this might now be worth the effort given that the system can already generate diurnal monthly means. The issue that arose for me is that I asked for the hourly files to be written out in history however the the gcm post script wasn't smart enough to clear them out from holding after the diurnal monthly mean was generated. I have since added a line to my build that deletes everything once it is no longer needed.
