### ISSUE TITLE
MAPL_Profiler has has an initialize/finalize can cause name collisions if exposed

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1773]
I tried to add the module "MAPL_Profiler" to MAPL.F90 so that the profiling library could be exposed via a simple "use MAPL" statement. However the MAPL_Profiler module itself defines a public initialize and finalize them so any other code that decides to use initialize or finalize locally as a procedure name will have a name collision. I found that a module used by ExtDataDriver.x defines a private initialize and finalize that adding the MAPL_profiler to MAPL.F90 results in a name collision.

This sounds so familiar. Should the initialize and finalize in MAPL_Profiler.F90 be renamed so something less generic to avoid name collosions?

**Comment by tclune** [comment]
The ideal solution to this is to use a Fortran generic interface around each specific procedure, ala:
```
interface initialize
   module procedure initialize_profiler
end interface
```
The problem is more perverse though, if they share interfaces.   E.g., if `initialize()` or `finalize()` do not take any arguments (or maybe just an optional return code), then this approach does not work.   In that case, one must either change the name in the code or use the Fortran rename mechanism `..., only:  a => b`    And possibly break backward compatibility.

The problem is more general, as I would like an initialize procedure for most layers in MAPL to properly encapsulate the responsibilities invoked at the top level.   So an analysis of what arguments are needed (or could be artificially added to disambiguate) is the 1st step.

**Comment by tclune** [comment]
There is probably a good reason to have a true MAPL object that encapsulates at least the "generic" aspects of MAPL.   But that is not the way our interfaces currently look, and it is not friendly to ESMF componentization without making it global.  So some of the issue here is the Gordian knot of interfacing different frameworks.

**Comment by tclune** [comment]
@bena-nasa Any thought on which of these options is viable?  If we have to use the longer name, so be it.

**Comment by bena-nasa** [comment]
@tclune, I just added this in MAPL.F90 for now
```
   use MAPL_Profiler, initialize_profiler =>initialize, finalize_profiler =>finalize
```

**Comment by mathomp4** [comment]
I want to say we fixed this at some point? @bena-nasa do you remember?
