### ISSUE TITLE
FEER biomass burning data : Data values are only 0 and -9999?

### ISSUE THREAD

**Issue by zhaosy123** [GEOS-ESM/MAPL#1891]
Hi! 
I want to download FEER biomass combustion data as my academic research data. But the data I downloaded from the official website seems wrong, the data values only have 0 and -9999 values. Does anyone have the same problem please?
The data is "FEER v1.0-G1.0"/"FEER v1.0-G1.2" daily or monthly dataset.[https://feer.gsfc.nasa.gov/data/emissions/](url)

**Comment by mathomp4** [comment]
@zhaosy123 Hmm. This might not be the right place for this. MAPL is just an infrastructure layer for GEOS. Indeed, I don't think GEOS' GOCART even uses FEER.

That said, I grabbed [FEERv1.0-G1.2_Daily_2021.nc](https://feer.gsfc.nasa.gov/data/emissions/v1.0/Emissions-archive/FEERv1.0-G1.2/DAILY/FEERv1.0-G1.2_Daily_2021.nc) and per `cdo infon` it has non-missing values:
```
$ cdo infon FEERv1.0-G1.2_Daily_2021.nc
cdo: /lib64/libcrypto.so.1.0.0: no version information available (required by cdo)
cdo: /lib64/libssl.so.1.0.0: no version information available (required by cdo)
Warning (cdfInqContents): Coordinates variable time can't be assigned!
    -1 :       Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter name
     1 : 2021-01-01 00:00:00       0  6480000 6476262 :  1.8513e-12  6.9619e-10  5.2787e-08 : AcOH
     2 : 2021-01-01 00:00:00 6.36408e+07  6480000 6476262 :  4.3030e-13  9.5610e-11  6.4991e-09 : Acet
     3 : 2021-01-01 00:00:00 6.36422e+07  6480000 6476462 :  4.3030e-13  1.0389e-10  1.6563e-08 : Acet
...
```

I mean *most* are missing since the world isn't totally on fire, but for each "level" (aka `time_old`) there are a few fires happening.
