### ISSUE TITLE
A few fixes for MAPL_GetResource

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#1955]
There are a few entries in the new module like:
https://github.com/GEOS-ESM/MAPL/blob/d42853ed7c1b907ecbbf8f514ff11d6aaee2242a/base/MAPL_Resource.F90#L168-L171

A cleaner implementation is to use either `_ASSERT` or `_FAIL` macros
```
_ASSERT(label_is_present .or. default_is_present, 'Must provide a label or a default.')
```
or
```
      if (.not. label_is_present .and. .not. default_is_present) then
         _FAIL('Must provide a label or a default.')
      end if
```

There are at least 2 occurrences of this pattern.

**Comment by darianboggs** [comment]
Because of client use-cases for `MAPL_GetResource`, it is important that the procedure _does not_ throw an exception for this particular condition (`.not. label_is_present .and. .not. default_is_present`). In other cases, it is appropriate for the procedure to throw an exception. So I'm closing this issue.
