### ISSUE TITLE
[QUESTION] Does MAPL ExtData properly handling NOLEAP data sets?

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#1983]
This is a hypothetical question since I have not tried using a 365-day dataset with MAPL. However, I have a question from a GEOS-Chem user who has a dataset that does not include leap days. The calendar metadata in the file is "365-day" and the time is measured as days since 1750 (but excluding leap days). If the file calendar metadata was changed to the more standard "NOLEAP" would MAPL correctly interpret the file times?

I have looked around the code but have not seen where the calendar metadata is stored, or even if it is read. I see where the model calendar is set in Cap, but the file calendar could be different from that.

**Comment by mathomp4** [comment]
Assigning @bena-nasa as I think he is the only one of us with a chance to answer this!

**Comment by bena-nasa** [comment]
@lizziel What are they trying to do with this dataset? Do they have just a single year? Or since you say it starts at 1750, it is a multi year dataset?

Are they trying to use it in "real" time, i.e. you are not extrapolating outside the dataset? So if the dataset runs from t1 to t2, the application is only running in that interval.
Or are they trying to use this dataset and extrapolate outside of it, either as a climatology for a particular year if it is multiple years, or just persist?

The calendar is set way up in the cap. I've never looked at ESMF's calendar API and did not know that you could even exclude the leap days.

The answer is this is just so far out from left field I have no idea, probably not, just because one dataset is missing the leap day, what if another is not. You can only have one calendar...


Can't they just write a script and add the leap days in to these NetCDF files? That seems like it would be easiest.

**Comment by lizziel** [comment]
Thanks @bena-nasa, this answers my question well enough. We don't have this handling in HEMCO I/O and it sounds like it is so non-standard it is not worth adding given it is not in MAPL either. Changing the file to include leap days seems easiest path.

However, this does raise the question of whether all input files are assumed to use the same calendar as the model calendar. There are many CF-compliant calendar options (see [here](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch04s04.html)), and you would presumably need to know it to accurately compute the next time in the file given a base time and time increment. The CF docs recommend using calendar for precisely this reason. Is it okay that it is ignored? Maybe there should be a warning if the calendar attribute is present and it is something that is not supported?

**Comment by mathomp4** [comment]
I looked at ESMF's docs and while they can make a noleap calendar, [they do say](https://earthsystemmodeling.org/docs/release/latest/ESMF_refdoc/node6.html#SECTION06040000000000000000):

> 41.4 Restrictions and Future Work
> ...
> Calendar date conversions. Date conversions are currently defined between the Gregorian, Julian, Julian Day, and Modified Julian Day calendars. Further research and work would need to be done to determine conversion algorithms with and between the other calendars: No Leap, 360 Day, and Custom.

So even if we could read in a noleap data set, there would be no way to convert to Gregorian (easily).

---

Side note, I liked this:

> ESMF_CALKIND_GREGORIAN
> Valid range: 3/1/4801 BC to 10/29/292,277,019,914

That's some...long-range forecasting there 😄

**Comment by mathomp4** [comment]
I'm going to close this as wontfix for now.
