### ISSUE TITLE
Does `MAPL_GetGrid` support any layout set by user?

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/MAPL#2010]
This is a question (as labeled).

@zhaobin74 reported following contradictory statements on teams and when I looked up the code for `MAPL_GetGrid` this [block](https://github.com/GEOS-ESM/MAPL/blob/43d92e9544383c9399b8851289b693072369e7f5/base/MaplGrid.F90#L271-L326) made me very curious to raise this question:

```
[10:20 AM] Zhao, Bin (GSFC-610.1)[SCIENCE APPLICATION INTL CORP]
    Akella, Santha (GSFC-6101)and Vikhliaev, Yury V. (GSFC-610.1)[SCIENCE SYSTEMS AND APPLICATIONS INC], thanks for putting together this configuration. I am able to run partially coupled CICE6 with this grid (using Yury's restart + CICE6). This will help me test CICE6 in a more realistic environment. As we know, the layout is a bit difficult because the y-dimension. I checked CICE6 and CICE4 code and see there is a way to get around of the limitation and make it flexible. I have implemented the fix in CICE6 and will get it done in CICE4 with a PR. **However, right now the model died in MAPL if a non-even decomposition (e.g. 10x9) is used. I pinged Atanas and he said MAPL supports non-even layout and it should be an easy fix.**     
```

and

```
[12:16 PM] Zhao, Bin (GSFC-610.1)[SCIENCE APPLICATION INTL CORP]
    **Atanas provided a fix in MAPL and it worked**. Now the model died in MOM6 initialize (https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/fdbb0f299823457403f0508ab8d03dc2b13abb08/MOM6_GEOSPlug/MOM6_GEOSPlug.F90#L354)
EditedGEOS_OceanGridComp/MOM6_GEOSPlug.F90 at fdbb0f299823457403f0508ab8d03dc2b13abb08 · GEOS-ESM/GEOS_OceanGridCompGEOS Ocean Gridded Component. Contribute to GEOS-ESM/GEOS_OceanGridComp development by creating an account on GitHub.github.com
```

- If `MAPL can support an odd layout`, what is there `to be an easy fix`??
- Also why are _fixes_ or _patches_ being provided in ways that cannot be traced across developers? I mean, I need to know about this via an issue: problem and whatever is/was fix.
- I would also like to get an explanation of this [block](https://github.com/GEOS-ESM/MAPL/blob/43d92e9544383c9399b8851289b693072369e7f5/base/MaplGrid.F90#L271-L326) (so it is recorded here in this issue).

Note:
- AFAIK we have always had even layouts and this time when @zhaobin74 tried a decomposition (see ⬆️ ) there is a crash from `MAPL_GetGrid`. Why??
- Crash location as @zhaobin74  said is at  https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/fdbb0f299823457403f0508ab8d03dc2b13abb08/MOM6_GEOSPlug/MOM6_GEOSPlug.F90#L348-L354

Thanks in advance for answering/addressing this question.

**Comment by tclune** [comment]
@atrayano please update this ticket.

**Comment by atrayano** [comment]
@sanAkel Here is my view of the situation: MAPL has its own rules how to decompose a grid, given a particular layout. It tries to divide the domain into sub-domains as evenly as possible, and then the "excess" is spread among the first processors. This is the default behavior. We could also prescribe a particular domain decomposition through the resource file. Once the domain is decomposed, we create an ESMF grid. MAPL_GridGet **only**  queries this grid and reports back, either the local subdomain sizes, or the global IM_WORLD, JM_WORLD. This is controlled be appropriate arguments to the call above. That being said, in the coupled model scenario, each of MOM (or MOM6) and CICE (both CICE4 and CICE6), have their "own" internal rules how to decompose the grid. Luckily for us (until now), the grid(s) divide evenly, and the three parties (MAPL, MOM, CICE) agree. Moreover, until MOM6, there was a requirement that the tripolar grid sub-domain are evenly divided, and this resulted in "enforcement" in MAPL of that fact. (The 2 _ASSERT statements are still in MAPL_TripolarGridFactory.F90, it is safe to uncomment them, but only when we have a plan how bring everybody on board).

So, MAPL_GridGet does support uneven grid distribution. But it is not MAPL job to "orchestrate" the agreement between MAPL/ESMF, ocean and sea-ice grids. As @tclune  refers to the current situation as agreement-by-coincidence. Again, MAPL does support uneven grid decompositions (both creation and queries). But currently, neither ocean, nor sea ice model query the ESMF grid to make sure, at the very least, that they agree to what is given to them. For that matter, we have similar situation with the FV dycore. I had some additional discussions with @zhaobin74 , and if I understand correctly, it is possible (in theory) to bring sea ice and MAPL in agreement. I am nearly 100% sure that FMS has some flexibility how to distribute the grid, but it has been a while since I looked into this.

My 2 cents: this is very important issue, but I would suggest closing this ticket.  This is not a MAPL issue, and definitely not MAPL_Get issue. We need a plan how to coordinate the grid creation in GEOS, and make sure that the grid is good for everybody.

P.S. I will be on personal travel Mon-Thu next week, so I might not respond to any comment(s) until I am back

**Comment by sanAkel** [comment]
Thank you @atrayano for taking time to reply. I would like to keep this issue open and when you are _back_ from travel, and _settled_, address a pathway towards a **solution** (see ⬇️) . Few questions follow:

> MAPL has its own rules how to decompose a grid, given a particular layout. It tries to divide the domain into sub-domains as evenly as possible,

Point to the `MAPL` source code where this `It tries to divide the domain into sub-domains as evenly as possible,` is done.

> We could also prescribe a particular domain decomposition through the resource file.

Can you give an example `rc` file, showing how it can be set?


> The 2 _ASSERT statements are still in MAPL_TripolarGridFactory.F90, it is safe to uncomment them, but only when we have a plan how bring everybody on board

Are you referring to https://github.com/GEOS-ESM/MAPL/blob/ee50e8c2949c18ca4f5f11e64cc19ab0b35227c3/base/MAPL_TripolarGridFactory.F90#L492-L493 ?


> But currently, neither ocean, nor sea ice model query the ESMF grid to make sure, at the very least, that they agree to what is given to them.

Can you or @tclune point me to which `ESMF` routine needs to be called to `query the ESMF grid`?

My **suggested** solution:

1. For any `odd` layout that we choose, `prescribe a particular domain decomposition through the resource file.` in the experiment configuration (directory). If such file is _present_, read it and do what needs to be done in `MAPL`, i.e. `create an ESMF grid`.
2. We (@sanAkel and @zhaobin74 ) make sure that the `particular domain decomposition through the resource file` (above 1) is same as what `MOM6` and `CICE6` also use to set their layouts.

This seems to be trivial to implement, isn't it? @tclune can you help while @atrayano is away? Me and if needed @mathomp4 can test our low res test case.
