### ISSUE TITLE
Wildcard support in History (ala GCHP)

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#210]
Allow choosing collections of tracers with certain characteristic based upon the name.   Would not hurt to have Harvard crowd add examples to the ticket.

**Comment by lizziel** [comment]
Sure. Here is a sample of GEOS-Chem Classic HISTORY.rc collections that use wildcards. Note that the file emulates what is in GEOS but not all fields are used, such as the gridcomp name and format CFIO. But we do use template, freq, duration, mode, and fields.
 
#=====================================================================
# %%%%% THE SpeciesConc COLLECTION %%%%%
# GEOS-Chem species concentrations (default = advected species)
#=====================================================================
  SpeciesConc.template:       '%y4%m2%d2_%h2%n2z.nc4',
  SpeciesConc.format:         'CFIO',
  SpeciesConc.frequency:      010000
  SpeciesConc.duration:       010000
  SpeciesConc.mode:           'time-averaged'
  SpeciesConc.fields:         'SpeciesConc_?ADV?             ', 'GIGCchem',
::
#=====================================================================
# %%%%% THE DryDep COLLECTION %%%%%
# Dry depositon fluxes and velocities (for all dry-depositing species)
#=====================================================================
  DryDep.template:            '%y4%m2%d2_%h2%n2z.nc4',
  DryDep.format:              'CFIO',
  DryDep.frequency:           010000
  DryDep.duration:            010000
  DryDep.mode:                'time-averaged'
  DryDep.fields:              'DryDepVel_?DRY?               ', 'GIGCchem',
                              'DryDepMix_?DRY?               ', 'GIGCchem',
                              'DryDepChm_?DRY?               ', 'GIGCchem',
                              'DryDep_?DRY?                  ', 'GIGCchem',
::
 
The way this works is as follows, explained with case SpeciesConc:
 
HISTORY.rc is parsed at the start of the run. For each unique name a DgnItem object is created and added to a linked list:
  TYPE, PUBLIC :: DgnItem
     CHARACTER(LEN=63)      :: name
     CHARACTER(LEN=63)      :: state
     CHARACTER(LEN=63)      :: metadataID
     CHARACTER(LEN=63)      :: registryID
     LOGICAL                :: isWildcard
     CHARACTER(LEN=7)       :: wildcard
     LOGICAL                :: isTagged
     CHARACTER(LEN=63)      :: tag
     ! could also add a list of collections this diagnostic is part of                   
     TYPE(DgnItem), POINTER :: next
  END TYPE DgnItem
 
For the case of SpeciesConc_?ADV?, since it has ? indicating wildcard, the string will be parsed in various ways. The important part to know is that ‘SpeciesConc’ will be the identifying string for the diagnostic, isWildcard is true, and ‘ADV’ will be the wildcard. Aside: If I had SpeciesConc_O3 instead, then there would be no wildcard but isTagged would be true and tag would be O3. This is what I do for GCHP.
 
‘SpeciesConc’ is then stored in an array with other names from HISTORY.rc. Its presence triggers allocation of a 4D array for storing species concentration in the model in a certain unit to be output.
 
When the 4D array is initialized, the 4th dimension will have size equal to a value (N) associated with the wildcard name. For SpeciesConc it is the total number of advected species determined at run-time, found in State_Chm%nAdvect.
 
After the 4D array is allocated, then N “registry” objects are created, each containing a pointer to a 3D subset of the 4D array and containing metadata about the diagnostic. Each has a name associated with it equal to the diagnostic name to appear in the output collection file. The name is constructed by appending species abbreviation to the prefix, separated with an underscore. The species abbreviations are retrieved in a loop over an index mapping array specific to the wildcard. For SpeciesConc this is a loop from 1 to State_Chm%nAdvect.
 
All of the above works for GCHP. Here is where things get different between GC Classic and MAPL and things stop working. GC Classic has a history component built to emulate MAPL history. It parses HISTORY.rc again to get collection information. It contains its own parsing of wildcards and taps into the same subroutines to get information about them as used for allocating diagnostic arrays in step 3. For the case of the SpeciesConc collection above, there would be an object containing an accumulator for each of the N species associated with wildcard ADV, with the same name as used in the “registry” (see step 5).
 
The bottleneck is that MAPL does not understand to make multiple exports for a line with a wildcard, and would not know how many to make or what to call them.  So it is step 6 that I needs implementing in MAPL in some form. I am okay with removing the meaning of the specific wildcard name and instead outputting all state names that start with whatever prefix is front of ?ADV?. In GCHP we never have state name overlap. To keep the rest of GCHP functional we would need to keep usage of format ?*? where * could be ignored by MAPL (e.g. could be DRY or ADV without causing an error).

Let me know if you have questions.

**Comment by lizziel** [comment]
@tclune and @atrayano , what is the status of work on this? Would it be possible to be available by June?

**Comment by atrayano** [comment]
Lizzie, I should be able to give you some beta version soonish (in the next 1-2 weeks)


On Mar 13, 2020, at 2:28 PM, Lizzie Lundgren <notifications@github.com<mailto:notifications@github.com>> wrote:



@tclune<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tclune&d=DwMCaQ&c=ApwzowJNAKKw3xye91w7BE1XMRKi2LN9kiMk5Csz9Zk&r=_r6-SBvtAqSGH0t7NYy2fPpq1wyPKQV-8ZiMEmovLb4&m=NSrTn8O9rFGhTXL2RU7aDYpo0LC3M9tigVGwtjTjQCo&s=zpPrslmdShLv9dG5D5KIIxl6csTr-x8YYYxc9VwJLE8&e=> and @atrayano<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_atrayano&d=DwMCaQ&c=ApwzowJNAKKw3xye91w7BE1XMRKi2LN9kiMk5Csz9Zk&r=_r6-SBvtAqSGH0t7NYy2fPpq1wyPKQV-8ZiMEmovLb4&m=NSrTn8O9rFGhTXL2RU7aDYpo0LC3M9tigVGwtjTjQCo&s=vMoc_SnZGQVYgydknExpwaM-yCeGc1J32o8JMmBBSAw&e=> , what is the status of work on this? Would it be possible to be available by June?

**Comment by lizziel** [comment]
Excellent. I look forward to testing it out!

**Comment by tclune** [comment]
@atrayano  - can this be closed?   Or are we waiting for @lizziel to evaluate

**Comment by atrayano** [comment]
@tclune let's close it. If needed, we always can open a new issue

**Comment by tclune** [comment]
Then close it ...

**Comment by lizziel** [comment]
This is still on my radar but has taken a backseat to other things. Once I turn my attention to it again and test I will reopen as needed.
