### ISSUE TITLE
Support for writing varaible slices in HISTORY.rc

### ISSUE THREAD

**Issue by gmao-esherman** [GEOS-ESM/MAPL#211]
Support for specifying variables slices in HISTORY.rc is requested. This request is part of refactoring GOCART so EXPORTS from GOCART's children can have the same name and utilize a 'nbins' dimension.

**Comment by lizziel** [comment]
I am curious if this feature request is something that could be useful to GEOS-Chem as well. @gmao-esherman , could you elaborate on what this is in a generic sense? For example, what are the variables registered as exports versus the array output you want to get?

**Comment by tclune** [comment]
Expanding a bit:   The idea is to allow fields in GOCART that have multiple bins to be represented as arrays in Fortran with the last extra dimension being of size n_bins.   But then allow each bin to be output into a separate netcdf  variable in history.   E.g. a surface field with 5 bins might be declared as a 3D array in GOCART as  

```
     call MAPL_AddImportSpec('q', ...., ungridded=[n_bins])
```

and then in history have 5  2D outputs with short names:    "q_001", "q_002", ...

**Comment by lizziel** [comment]
This would definitely be useful in GEOS-Chem since we carry a lot of our state arrays in this form. Right now I assemble a linked list of all the history entries and do a lot of pattern matching to figure out how our state array slices map to each import. If we could have each of our state variables map to a single import array, rather than map to a whole bunch, that would be cleaner.

This is also related to the wildcard feature I requested from Atanas. For that update I wanted history to automatically output all exports with name containing a certain prefix followed by an underscore and a substring containing question marks. For example, our species concentration entry in HISTORY.rc would be SpeciesConc_?SPC?. Our SpeciesConc array is 4D, but history would output a bunch of 3D arrays, one for each index in the 4th dimension. With this feature request you could do something like that too. You can even take it further and have multiple wildcard options, e.g. we also have ?DRY? and ?WET? to output only dry and wet deposited species. I think this might be useful to you beyond GOCART.

**Comment by mathomp4** [comment]
@atrayano Can this be closed? I want to say you've done this (or part of it)? If so, a new issue could be opened with what is needed.

Or is there a new issue??

**Comment by atrayano** [comment]
@mathomp4 , I think this can be closed. I've done several iterations and the latest version addressed all requests by Arlindo and Elliot

**Comment by gmao-esherman** [comment]
Yes, this can be closed. The feature request has been addressed.

**Comment by lizziel** [comment]
Could you link to documentation for the feature, either the PR or a related issue that details it?

**Comment by gmao-esherman** [comment]
Unfortunately I don't know of any documentation for this feature.

To use this feature please add "collection_name:splitFIeld: 1" to the collection parameters. This will take the ungridded dimension of a variable and serialize it. The serialized variable(s) will have "00n" appended to the variable name. Please see example below.

DU(x,y,z,ungridded) --> DU001(x,y,z), DU002(x,y,z), ... DU00n(x,y,z)
