### ISSUE TITLE
Feature request: set ESMF logging mode at run-time via config file

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#2133]
The ESMF logging mode is currently part of `cap_options` set via a command line tool. We do not use the command line tool in GCHP and so set the logging mode at a very high level to pass when creating MAPL CAP (see [here](https://github.com/geoschem/GCHP/blob/0345abf5cb237a72e0fc33873263f6618ff3e16b/src/GCHPctm.F90#L29)). To change the logging mode, such as to disable the default `ESMF_LOGKIND_MULTI_ON_ERROR`, users need to change the code and recompile. 

It would be more convenient to set the logging mode at run-time via a config file. This is not possible with the current implementation of MAPL, however, because the logging mode is needed for ESMF initialization (see [here](https://github.com/GEOS-ESM/MAPL/blob/5545f08d47514b2af409966a80f7e67af9d26320/gridcomps/Cap/MAPL_Cap.F90#LL281C53-L281C53)) but ESMF initialization needs to happen prior to reading a config file.

The solution to this problem is to pass a config file rather than logging string to `ESMF_Initialize`. This is possible according to the [ESMF docs](http://earthsystemmodeling.org/docs/release/latest/ESMF_refdoc/node4.html#SECTION04024100000000000000).

**Comment by mathomp4** [comment]
@lizziel I'm assigning @tclune and @bena-nasa to answer this more. They'd have the knowledge on how and if this could be done.

**Comment by lizziel** [comment]
Thanks @mathomp4. I should give credit to @tclune (or was it @bena-nasa?) for coming up with the idea to pass a config file to `ESMF_Initialize`. We discussed solutions at our MAPL meeting earlier this week so they knew this feature request was coming.

**Comment by bena-nasa** [comment]
@lizziel so you want to parse from something YAML? Plain ASCII? ESMF_Config( which of course you can't parse with ESMF_Config at that point)? before that call where you set the logging mode in CapOptions?

**Comment by mathomp4** [comment]
Ben is out today, but I have some time because the work I was doing at NAS needs sysadmin help. So I took a shot at this. I have a branch called `feature/mathomp4/2133-pre-esmf-file` ([see changes here](https://github.com/GEOS-ESM/MAPL/compare/develop...feature/mathomp4/2133-pre-esmf-file)) where you can have a file named `ESMF.rc` that looks like:
```
$ cat ESMF.rc
logKindFlag: ESMF_LOGKIND_MULTI_ON_ERROR
```
and if it's present, it will read it and change the log level.

Now, in this branch (at least) the file *MUST* be named `ESMF.rc` because, well, I couldn't figure anything else out. (Since `CAP.rc` is parsed by ESMF, you can't put anything in there.)

@lizziel Can you try this branch and see how it works for you? If nothing else, it's a first go at this. We will probably wait for @bena-nasa to return and figure out something more elegant and permanent, but we can at least see if this works for you.

**Comment by lizziel** [comment]
Thanks @mathomp4. To be clear, this update is not urgent and something that I'd like in a future release that will eventually go into GCHP. I actually have a zero time to test unfortunately. At the meeting earlier this week Tom and I agreed on CAP.rc as the place to put the toggle.

**Comment by lizziel** [comment]
I'll know very soon. I am testing your updates today.

**Comment by lizziel** [comment]
This works! I'll put it into GCHP (and give you full credit). If you could merge it into MAPL before the 3 release that would be great.
