### ISSUE TITLE
MAPL Ford Docs failing to build on `main`

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#2142]
Something has happened on `main` to break Ford.

```
Preprocessing /home/runner/work/MAPL/MAPL/Ford/../geom/StateSupplement.F90
ERROR in file 'StateSupplement.F90': Unexpected INTERFACE in sourcefile 'StateSupplement.F90':
	interface write(formatted)
ERROR in file 'StateSupplement.F90': END statement outside of any nesting:
	end interface write(formatted)
```

It's possible Ford doesn't like Fortran programs that don't *start* with `program`?

We'll try and take a look at it.

**Comment by JulesKouatchou** [comment]
In my point of view, the first thing is to include the `program` statement and see if there is an improvement. I believe that the problem will go away.

**Comment by tclune** [comment]
Agreed.  Friendlier to the reader as well.    

Skipping the PROGRAM statement should only be used for code-golf.

**Comment by tclune** [comment]
And minimal reproducers.

**Comment by JulesKouatchou** [comment]
I am afraid that I may have to contact Ford developer for this error message. Based on:

https://stackoverflow.com/questions/47031967/django-str-object-has-no-attribute-meta

the error is due to Django and perhaps Ford needs to be modified to fix the problem.

**Comment by JulesKouatchou** [comment]
Here are the comments I received from the Ford developers:

----
Hi @JulesKouatchou, I think this is most likely due to the line

      procedure, deferred :: get_esmf_geom
in MaplGeom.F90. deferred procedures need an interface, something like:

      procedure(esmf_geom_interface), deferred :: get_esmf_geom
where esmf_geom_interface is some abstract interface.

Ideally ford would catch this sooner with a more helpful error message. I will try and fix that at some point!

----

I believe that for now, we can just generate documentation only from files (in the `geom/` folder) that are compiled.
