### ISSUE TITLE
Problem with new udunits2 Fortran interfaces

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#2550]
The Fortran interface provides two different interfaces for one global (extern) procedure.  NAG correctly flags this as an error.  For now I've commented out the former, but it needs discussion. (Have built, but have not tried running.)

https://github.com/GEOS-ESM/MAPL/blob/89b15816415c793b52a7ae551ca10c5adae3c360/field_utils/mapl_udunits2interfaces.F90#L26

https://github.com/GEOS-ESM/MAPL/blob/89b15816415c793b52a7ae551ca10c5adae3c360/field_utils/mapl_udunits2interfaces.F90#L35

**Comment by mathomp4** [comment]
This is interesting. We might just have to say "Fortran only supports the 'by environment variable'" version of this unless a workaround can be found.

Odd that both GNU and Intel seem happy about this.

**Comment by darianboggs** [comment]
True.

I propose we remove the path (`character(kind=c_char) :: path(*)`) interface.

That leaves the interface with `type(c_ptr) :: cptr` interface. That's all we need right now, and we can use that interface if we want to modify the unit system, later.

If we take this course, I will modify my code to only use the standard database with no option to provide an alternative path.

If we do want to modify the unit system, I propose we start with the standard unit database and modify it programmatically rather than create a custom unit database. The udunits2 documentation recommends the former solution.

I can elaborate on this and explain why I think users should not be specifying a custom unit database.

**Comment by mathomp4** [comment]
@darianboggs Is this still an issue?
