### ISSUE TITLE
Detect serial build of ESMF?

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#2553]
A recent GCHP issue might have been resolved more quickly if MAPL did a check to verify that ESMF has been built with MPI.   Please check to see if there is some query we could do (and then throw an error).

**Comment by bena-nasa** [comment]
@tclune  I'm not seeing anything in the API, either looking at the ESMF_VMGet or when you call ESM_Init, unless somehow if you don't build with MPI that maybe the MPIcommunicaor returned from ESMF_VMGet is always null?
@mathomp4 do we have a no/ MPIESMF build of baselibs we could play with?
Can you even build ESMF without MPI, I guess so, but not obvious from the documentation in my brief scanning.
Also, how can MAPL even function without MPI, it is so ubiquitous?

**Comment by tclune** [comment]
> Also, how can MAPL even function without MPI, it is so ubiquitous?

Well, you can't.  But the error that you get early on is not very informative.   And happens when doing analysis about cores-per-node or some such.    One possibility is just to change that message to indicate that MPIUNI is a likely culprit.

**Comment by mathomp4** [comment]
Let's consider two ways: build-time detection and run-time detection.

At build-time, from my staring at `FindESMF.cmake`, I don't think `ESMF_COMM` is exposed mainly because I don't think it's exposed in `esmf.mk`. It's in a comment, but commented entries are skipped. Now, I could probably hack `FindESMF.cmake` to also skip all commented lines but then also look for the one that is `# ESMF_COMM:`...

So then perhaps at run-time? But for that I probably need to invoke the names of @theurich and @oehmke and see if they have thoughts? Maybe there is some `ESMF_Initialize`-like call that acts differently under `mpiuni`?

Or maybe we add a CMake style `try_compile` where if the ESMF folks know of a call that fails under `mpiuni` we could say "Hey, this simple ESMF code failed, your ESMF must have been built as `mpiuni`" or the like.

**Comment by tclune** [comment]
We can query the VM and get `numPets`.  Not sure that works with MPIUNI, but by the interface we would expect a result of `1`.  The question then is what if we run say doubly-periodic on 1 core for testing purposes ....

Hopefully @theurich has a better solution.   We could ask for some patch to ESMF for this but that seems heavy for one problem by one student using a non GMAO application ...

**Comment by oehmke** [comment]
ESMF_VMGet() <http://earthsystemmodeling.org/docs/nightly/develop/ESMF_refdoc/node6.html#SECTION0601361800000000000000> has the argument esmfComm which is a string that contains the  value of the ESMF_COMM build environment variable. You could use that to check for: mpiuni

**Comment by mathomp4** [comment]
Ooh. Thanks @oehmke! I'll test it out with an mpiuni Baselibs I have around.

**Comment by oehmke** [comment]
You’re welcome! Let me know if it doesn’t do what you want.

**Comment by mathomp4** [comment]
> You’re welcome! Let me know if it doesn’t do what you want.

@oehmke I have a PR that seems to do it: https://github.com/GEOS-ESM/MAPL/pull/2556

But new question: how much do I need to belt-and-suspender this? For example, do I need to first call `ESMF_VMIsCreated`? Or is that just overkill in that a VM is always created after a successful `ESMF_Initialize` call (which is right above this)?

Also, is there a preference between using `ESMF_VMGetCurrent` vs `ESMF_VMGetGlobal`? Or perhaps a better call to get the VM should be used? 

I ask only because I rarely do ESMF coding and I figure I should do it "right" when I do. 😄

**Comment by theurich** [comment]
@mathomp4 - you are guaranteed a valid global VM after `ESMF_Initialize()` returns successfully. Right under `ESMF_Initialize()`, the current VM is identical to the global VM, so either of those calls would work.
Simpler even, just add the `vm` argument to your `ESMF_Initialize()` call, and it will return the global VM to you without any extra work. Then access `esmfComm` via [ESMF_VMGet()](https://earthsystemmodeling.org/docs/nightly/develop/ESMF_refdoc/node6.html#SECTION0601361800000000000000) as suggested by @oehmke, and you should be all set.

**Comment by mathomp4** [comment]
@theurich Oooh. Nice. One less call is always good! Thanks!
