### ISSUE TITLE
Issues writing at c5760 with Intel compilers

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2703]
I'm just making an issue here so we don't forget. Certainly seems to be an an Intel compiler issue. The problem is that once you try to write a 3D variable more than above say 10 or 11 levels the multigroup server crashes. This is not an out of memory issue. There is plenty of memory.

I have reproduced with ExtDataDriver.x  by configuring its export state with a single 3D variable and trying to write in History and turn on the multi group server. Here is an example of how to run if I use a 6x36 layout for the application with 2 o-server nodes.

Note all my tests have been on the Milan nodes at Discover.

```
mpirun -np 504 ExtDataDriver.x --npes_model 216 --oserver_type multigroup --nodes_output_server 2 --npes_backend_pernode  20
```

With the Intel compiler, so far with both 2021.6, with openmpi and 2021.11 with intempi, in both cases this fails once the variable has more than 10 or 11 levels like so:
```
libMAPL.pfio.so    000014E4D66169BF  pfio_multigroupse         807  MultiGroupServer.F90
libMAPL.pfio.so    000014E4D65E4A7A  pfio_multigroupse         451  MultiGroupServer.F90
libMAPL.pfio.so    000014E4D65C3D78  pfio_multigroupse         205  MultiGroupServer.F90
libMAPL.base.so    000014E4D8B94A03  mapl_servermanage         265  ServerManager.F90
ExtDataDriver.x    000000000048EA64  extdatadrivermod_         174  ExtDataDriverMod.F90
ExtDataDriver.x    0000000000489F84  extdatadrivermod_          93  ExtDataDriverMod.F90
ExtDataDriver.x    0000000000486823  MAIN__                     25  ExtDataDriver.F90
```

However, I just tried with gcc and the same run that failed with Intel succeeds with gcc13 and openmpi 5

@weiyuan-jiang thought there may be a compiler bug that was not present on the Milan's but only on the SLES12 system, his standalone reproducer what was thought to be the compiler issue he showed me seemed to working with these same compilers on the Milan's.

Nevertheless still seeing these server issues despite what the standalone code is doing.

**Comment by mathomp4** [comment]
Huh. GCC 13 works? Interesting. Might be time for another set of benchmarks. Intel 2021.11 vs GCC 13.

On the Milans, GCC does do pretty well!

**Comment by bena-nasa** [comment]
As suggested by @tclune rather than writing a single 3D variable, I tried writing multiple 2D variables at this 5760 resolution with the Intel build. So far I tried 25 2d variables and that has been working. This is well beyond where the equivalent 3D variable failed.

**Comment by weiyuan-jiang** [comment]
This is caused by ifort bug ( until 24.0.0), When the array size is large ( more than maxint),  the program below crashes.  We will come back to verify this program when Intel fixes it.

program main
   use, intrinsic :: iso_c_binding, only: c_ptr
   use, intrinsic :: iso_c_binding, only: c_loc
   use, intrinsic :: iso_fortran_env, only: INT32, INT64
   use, intrinsic :: iso_c_binding, only: c_f_pointer
   implicit none
   integer,  allocatable ::  buffer(:)
   class(*), allocatable, target :: x_alloc(:)
   integer, pointer ::  g_1d(:)
   type(c_ptr) ::  address
   class(*), pointer :: i_ptr(:)
   integer(kind=INT64) :: k
 
   k = 4294967296_INT64 ! 2**32
   !k = 4976640000_INT64 ! 5760*5760*6*25
   allocate(buffer(k), source=-1)
   allocate(x_alloc, source=buffer)
   i_ptr => x_alloc
   select type (ptr=>i_ptr)
      type is (integer(INT32))
         address = c_loc(ptr(1))
   end select
   call c_f_pointer(address, g_1d,  shape=[k])
   g_1d = 1
end program
