### ISSUE TITLE
Get logger/flogger working in MAPL3G in applications using Cap and CapGridComp

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2739]
We now have a basic application that exercises the MAPL3 cap and CapGridComp, to run a basic configurable component and the History skeleton. The History attempted to use the logger in the component. This failed so we need figure out what we need to do enable flogger and logging in MAPL3 applications.

**Comment by bena-nasa** [comment]
@tclune 
Is the logging nested, in that  I can see the SetService of the children happen before their parents so CapGridComp's Setservice happens last, is this problem for setting up the loggers in the first place. So if you try to use a logger in a child's SetServices, do we have problem since the parent's set service has not run yet?

In MAPL2 of course the we setup a logger in the CapGridComp before ever even adding any children.

**Comment by tclune** [comment]
The parent runs set services before its children.   This is necessary because the children do not even exist until the parent runs AddChild().

If there is a real problem, we could probably run the child setservices during AddChild(), but currently I have setservices() running in a non-recursive manner.   At the end of the parent's set services, the generic layer runs setservice on each of the children.

So ... CapGridComp's SetService() runs 1st.

But I'm not understanding your basic concern.  All that the logging system needs is the name of the logger.   Once we are in setservices, we know the name of our component and can retrieve the corresponding logger.

Activating this in MAPL3 should be relatively easy - even if it is a temporary kludge.   I'm still thinking about how I want to manage the handful of global/singleton objects needed by MAPL.

**Comment by tclune** [comment]
pflogger should be enabled when PR #2756 is merged.  Closing.
