### ISSUE TITLE
Spurious FileMetadata FAILs in MAPL3

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#2892]
In examining the failure in #2891, another oddity was seen. At History initialize, we get a *LOT* of `FAIL`:

```
 Freq: 00060000  Dur: 00060000  TM:   -1  Collection: geosgcm_prog
pe=00044 FAIL at line=00265    pfio/FileMetadata.F90                    <status=1>
pe=00044 FAIL at line=00265    pfio/FileMetadata.F90                    <status=1>
pe=00044 FAIL at line=00265    pfio/FileMetadata.F90                    <status=1>
```

This happens for *every* collection. 

I added a print in `get_variable` above this and it shows:
```
 MATMAT var_name = lons
 MATMAT var_name = lats
 MATMAT var_name = corner_lons
 MATMAT var_name = corner_lats
pe=00091 FAIL at line=00266    pfio/FileMetadata.F90                    <status=1>
pe=00091 FAIL at line=00266    pfio/FileMetadata.F90                    <status=1>
pe=00091 FAIL at line=00266    pfio/FileMetadata.F90                    <status=1>
pe=00091 FAIL at line=00266    pfio/FileMetadata.F90                    <status=1>
```

Since the traceback doesn't give more info, I'll pass along to @bena-nasa 

Note: these fails do not affect the run it seems and all works and is zero-diff past this (save #2891).

**Comment by bena-nasa** [comment]
The issue is that in `release/MAPL-v3`,`get_variable` has this line `var => this%variables%at(var_name, _RC)` with the `_RC` where at in main and develop this line does not have the `_RC` code.

Now in `GriddedIO.F90` in all those branches we have stuff like this:
```
   coord_var => this%metadata%get_variable('lons')
   if (associated(coord_var)) call coord_var%set_deflation(this%deflateLevel)
```
So if `lons` doesn't exist in the non mapl3 branches you get the unassociated pointer, in the mapl3 branches you still get the unassociated pointer but not the call to `get_variable` has thrown the error and you get all these prints.

@tclune must have been on an add `_RC` macro rampage in MAPL3 at some point. I guess the MAPL3 code can change to something like this?
```
   coord_var => this%metadata%get_variable('lons',_RC)
   if (associated(coord_var) .and. status=_SUCCESS) call coord_var%set_deflation(this%deflateLevel)
```

or just 
```
   coord_var => this%metadata%get_variable('lons',_RC)
   if (status=_SUCCESS) call coord_var%set_deflation(this%deflateLevel)
```

or one could debate it get_variable should even have a return code at all?

**Comment by tclune** [comment]
I suspect this is more due to conversion to gFTL2 than any other rampage.    In gFTL2 `map%of()` is "unsafe" but faster.  `map%at()` has a (mandatory) return code.    This is to better emulate the C++ STL interface.   I think for vectors `at()` remains optional due to some backward compatibility issue I did not want to face.  But maybe not.

**Comment by tclune** [comment]
> or one could debate it get_variable should even have a return code at all?

If it can fail, then there should be a return code.  And it should be checked.  Possible exception for performance critical code, which this is not.
