### ISSUE TITLE
StartTime in clockinit

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/MAPL#506]
I saw Matt used some random old dates as BEG_DATE which does't seem to matter but makes the start time useless because the program actually starts from "cap_restart" which is CurTime here in the call.  Can we use CurTime as the starttime?

@mathomp4 @atrayano 

https://github.com/GEOS-ESM/MAPL/blob/d1cb19d0d31fa0d55a5bcdb7ccdb9a0b1c738e21/base/MAPL_CapGridComp.F90#L1463-L1469

**Comment by mathomp4** [comment]
Yeeeeeesss? I know long ago I think the model would actually crash in very odd ways if you set `BEG_DATE` to be the *actual* start time. I'm pretty sure @atrayano fixed that back then. (I might have been doing something weird like running replay at the same time? Not sure.) My usual advice to people is that the `BEG_DATE` is pretty useless so keep it where it is since `cap_restart` is, as far as I'm concerned, the real start time.

**Comment by weiyuan-jiang** [comment]
Since "BEG_DATE is pretty useless" , I suggest we change the clockCreate call to  "startTime=CurTime" @atrayano

**Comment by atrayano** [comment]
@weiyuan-jiang I can argue that BEG_DATE/BEG_TIME is not useless. In the past, we needed the beginning date/time of the clock to be prior to the current time since we used to tick the clock one step backwards before initialize. And since begin and stop time determine the "validity" of the clock, it would been an error back then. If we ever need to tick the clock in reverse direction prior to the beginning time of the experiment (which we currently do not do) this would rigger an error

**Comment by weiyuan-jiang** [comment]
OK. There is an easy fix in GEOSldas to get the cap_restart time. It is current time during initialization. Thanks
