### ISSUE TITLE
[FEATURE REQUEST] Allow clobbering of existing NetCDF files

### ISSUE THREAD

**Issue by sdeastham** [GEOS-ESM/MAPL#640]
Currently MAPL fails if an attempt is made to create a new NetCDF file when one already exists in that location. However, this is problematic, as it can result in frustrating loss of productivity. For example, we (the GCHP developers) frequently perform a series of tests in the same working directory; adding lines to the run script which clear out the working directory and storage directories would resolve this but would also raise the possibility of users accidentally destroying their output directory and all existing checkpoints. This behavior is also internally inconsistent, as MAPL will happily "clobber" (technically, write over the data within) 3-D gridded output through HISTORY.rc, but will fail if asked to clobber a restart file or 1-D non-gridded output.

A helpful solution would be to have a switch which explicitly permits such clobbering, perhaps in CAP.rc or another resource file. This would prevent unwanted behavior in GEOS (where presumably this clobbering is not desired) but would be very helpful to the GCHP community.

Tagging @tclune, @atrayano, and @lizziel with whom this was previously discussed.

**Comment by bena-nasa** [comment]
I'm fine with changing the default behavior if that is better for you workflow. The fact that GEOS never fails because a file is in the way means our scripting is moving everything out of the way so I can't see a harm in changing the default. As you say, because of how History works there is inconsistency in the behavior anyway due to the fact that if a file exists in the pfio server side, it "opens" instead of "creates" which explains this. The restarts are different since they don't go through the server by default. I'll make a simple PR to change this. Making this a user flag is complicated by the fact that the layers where the "create" happens have no access to the resource files where they could look for a user setting and it is not clear this could be added without changing a lot of interfaces.

**Comment by lizziel** [comment]
Just seeing this issue for the first time now. To be clear, the new behavior will be such that a pre-existing restart file with the same name as configured in `AGCM.rc` (or `GCHP.rc` in our case, namely `gcchem_internal_checkpoint`) will NOT cause the run to crash. Can you confirm that?

I previously added code to GCHP run scripts to rename the restart to include timestamp and keyword "restart" to get around the issue, and make the naming more clear. The GEOS run script gcm_run.j does something similar. Resubmitting a run without renaming or deleting the restart with the default name would cause a crash, and I thought this was a needed feature for GEOS if I recall correctly. Has that changed?

@sdeastham, if overwriting the restart is now possible I think we should still rename the restart to keep it around between series of runs so it is not over-written. Only the checkpoints output using the `RECORD` keywords in `GCHP.rc` have time in their name.

**Comment by mathomp4** [comment]
I'm re-opening this and pinging @bena-nasa and @tclune. I closed it just because I saw a merged PR.

**Comment by tclune** [comment]
I have forgotten the reservations about allowing this.  Certainly the change to the source code is trivial.

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune

**Comment by lizziel** [comment]
I have been enjoying the new functionality. If you end up changing back please keep the overwrite capability as an option!
