### ISSUE TITLE
Bug: Floating divide by zero error when reading input volcanic emissions in GOCART/SU with UFS

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/MAPL#680]
A `floating divide by zero` error occurs in `MAPL_BaseMod > MAPL_GetHorzIJIndex() > cube_xy()` while reading in volcanic emissions in `GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90` when running UFS-GOCART built in debug mode on Orion. Relevant stack trace information are provided below:

```
forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source             
ufs_model          000000000A5E9C4B  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B512D4CB5D0  Unknown               Unknown  Unknown
ufs_model          00000000021385DB  mapl_basemodmapl_        3701  MAPL_Base.F90
ufs_model          0000000002134931  mapl_basemod_mp_m        3510  MAPL_Base.F90
ufs_model          0000000001DCAA5D  su2g_gridcompmod_         868  SU2G_GridCompMod.F90
ufs_model          0000000001DBC198  su2g_gridcompmod_         719  SU2G_GridCompMod.F90
```

The MAPL library (branch: `main`, revision `bc57d97c`) was built without debug flags and with `BUILD_WITH_FLAP=NO`.

**Comment by tclune** [comment]
I'm adding @bena-nasa to this ticket.    He's more experienced with GetHorzIJIndex for the CS grid.

@rmontuoro - any clue as to what was different about this particular run?   Clearly GOCART has run successfully many times, and no changes have been made recently in  that bottom most routine.

**Comment by tclune** [comment]
The division at that line has `SIN(LAT)` as the denominator.    Presumably the CS grids in GEOS don't quite have points right at the pole (cell corner is at pole, but centers are slightly displaced), but the NOAA CS grid does.   (But this surprises me, since we nominally both get our grids from the FMS / FV layer.)      

Aside from this, the code in MAPL should not need to do such divisions.   I would expect a robust algorithm could be implemented that just checks for inclusion within specific regions.      I could be wrong though.

**Comment by bena-nasa** [comment]
I talked with Rafeale and Williams yesterday. We found a couple things, for example the grid coming in from UFS is in degrees, this assumes the points were radians. There were a few other assumptions in there (the fuji rotation) Also this is not using the centers, only the corners.

This needs to be rewritten to be more robust in any case. What is the trig to tell if a point is in a rectangular polygon defined by great circles. That would avoid what I did here where I convert to the 2D cartesian points on the face and search there.

**Comment by tclune** [comment]
Are  the coordinates for the grid or for the volcano emissions?

**Comment by bena-nasa** [comment]
This takes an arbitrary list of coordinates and an ESMF grid. Then for each coordinate we want to know, is it in the local domain? If so what are the indices of the cell in that domain that contain that point so you have to search. So there are two coordinate sets the grid and the arbitrary list of points.

I thought maybe ESMF locstream -> grid transform could do this but I'm not thinking so since we want to really aggregate points in each cell, not simply sample say the nearest.

**Comment by tclune** [comment]
Overall, the current approach also seems expensive.    E.g., there may just be 1 volcano at a given time, and yet essentially all the entire grid is brought into memory.      I'm wondering if the C5760 runs are being impacted by this?

If ESMF regridding can do the job, great.   Otherwise, a bisection algorithm will significantly reduce the cost without requiring any unsafe divisions.

**Comment by bena-nasa** [comment]
Bill said he is not running gocart for c5760 run

**Comment by rmontuoro** [comment]
@tclune - this test run is using volcanic emissions, which were not included in previous runs.

Transforming the grid coordinates to radians fixed the problem, however a more general strategy is needed to properly handle:

**(a) coordinate units**

- Option 1: MAPL could check the coordinate units and perform a proper conversion. This needs to be done both in `base/MAPL_Base.F90` and `base/MAPL_OrbGridCompMod.F90` (code replication):
```
        call ESMF_GridGet(grid, coordSys=coordSys, rc=status)
        _VERIFY(STATUS)
        if      (coordSys == ESMF_COORDSYS_SPH_DEG) then
          conv = PI_R8 / 180._ESMF_KIND_R8
        else if (coordSys == ESMF_COORDSYS_SPH_RAD) then
          conv = 1._ESMF_KIND_R8
        else
          _ASSERT(.false., "unsupported coordinate system")
        end if
        ...
              EdgeLons_ = conv * EdgeLons_
              EdgeLats_ = conv * EdgeLats_
```
- Option 2: MAPL could create a deep copy of the external grid, converting the coordinates to radians if needed

**(b) coordinate shift (Fuji rotation)**

- The UFS global cubed sphere grid is indeed shifted away from Japan and the default setting is consistent with the correction implemented in MAPL:
```
        LAT=LATS(I,J)
        LON=LONS(I,J)+MAPL_PI_R8/18.0d0
```
Since we are allowing MAPL to use external grid, however, a more general approach should be implemented. Not sure how to determine the shift from the grid itself. Could such a shift be bypassed in `cube_xy()` and related methods?

**Comment by bena-nasa** [comment]
I'm just going to try to implement a more general algorithm for the cube. So hopefully that should make the shifting irrelevant. You can apparently retrieve the coordinate type with a MAPL_GridGet call so that can take care of any radians/degrees confusion for anything needing to use the coordinates. I'm going to work on this now so hang tight.

**Comment by rmontuoro** [comment]
Thanks a lot @bena-nasa! I look forward to the new implementation.

The question on whether we should create a full copy of the external grid for MAPL still remains, and may help address this issue. What's your preference?

**Comment by bena-nasa** [comment]
No, I don't think you need to make a full copy.  We can determine the coordinate type so no need to make a copy with different units.

**Comment by tclune** [comment]
The actual offset used should not affect the algorithm.  The grid is a set of coordinates and we're just implementing an (efficient) search to find the cell that contains a given point.      I'd otherwise hate to try to "guess" the offset from data.

Even the radians issue will probably evaporate once the new algorithm is in place.        I may need to better understand how/if ESMF detects radians vs degrees when doing regridding though.   Apparently that has been working so somehow ESMF must be able to detect this.

**Comment by rokuingh** [comment]
ESMF regridding is done in Cartesian coordinates. The coordinate system of the Grid, Mesh or LocStream that is being used to represent the coordinates of the data that is being regridded is specified at creation time.

**Comment by bena-nasa** [comment]
Making this contingent for now. When I ran both algorithms simultaneously and compared the assigned indices it never complained that they did not match. But now after stripping out the old algorithm I'm finding it is non-zero diff so I'm confused. I'll do some more checking but keep the PR as DNA to save retyping later.

**Comment by bena-nasa** [comment]
I just made a PR to the develop branch of MAPL that should fix this. I generalized the search, no assumptions about rotations, when I grab the full corners I need to do the search that I now store in the grid (they have to so somewhere) if they were created as degrees, I convert to radians.

**Comment by mathomp4** [comment]
Closing this as (for some reason) the autocloser didn't work...

**Comment by bena-nasa** [comment]
Reopening as there was still a bug in the updated implemention

**Comment by bena-nasa** [comment]
Yes this should be fixed
