### ISSUE TITLE
Pull master into develop: whither version?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#7]
We've been making some minor updates to `master` that should now be merged back into develop. A test pull request #6 shows that there are conflicts in `CMakeLists.txt` files. One is the `CMakeLists.txt` in `MAPL_Base` and that makes sense since `develop` as different files. Fine.

The one I'm wondering about is the base-level `CMakeLists.txt` and it's a question for @tclune. That file is conflicting on the version number for the project. I assume that Project Version numbers only change on `master` and so `develop` should always reflect that version? Or should `develop` have a different version?

**Comment by mathomp4** [comment]
Thinking in semver ways, it seems like `develop` should be v2.0.0-based as, well, it does break compatibility! But, do you version a non-released CMake PROJECT?

**Comment by tclune** [comment]
This issue makes my head hurt.

Since we've never released it separately, I don't think the "backward" compatible issue really applies.   If we had been doing things more carefully we could/should have done  0.y.z until our first real release.   Non backward-compatible changes are allowed for "0".

I just had not read the document when we started.
