### ISSUE TITLE
Active timing measurements may impact performance due to excessive task synchronization

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/MAPL#724]
Several calls to `ESMF_VMBarrier()`, used for timing purposes, may negatively impact runtime performance of MAPL-based applications due to excessive task synchronization.

I'd like to propose adding an option (perhaps to `MAPL_CapOptions`) to disable component timing. Timing-related code as well as calls to `ESMF_VMBarrier()` could, for instance, be wrapped with additional MAPL APIs which would invoke/skip the synchronization barrier according to the option provided.

**Comment by tclune** [comment]
I'm sympathetic in principle but am wary of whether there is a one-size-fits-all solution.   Perhaps some of these barriers have additional rationale.     Further, I suspect some of these serve no purpose and all and should simply be removed rather than changing to a wrapper.      (I'm also a bit skeptical that the performance impact is even measurable for the GOCART use case - but I could be wrong.)

The timers in CapGridComp itself are not typical for GEOS and were added by the model developers to get a throughput measure independent of the main profiling capabilities used in MAPL.    But as near as I can tell these atypical timers only involve the root process and thus don't need the barrier at all.    

The barrier before writing the EGRESS file is essential and should not be turned off.    At most it should have a separate switch if it really is a problem on the NOAA end.

I've assigned a couple more people in the group in case they have some memory for why some of these barriers exist.

**Comment by atrayano** [comment]
@rmontuoro you can disable component timing with the existing MAPL. While the timing is turned on by default, in MAPL_CapGridComp.F90 we call MAPL_ProfDisable if enableTimers was not set to "YES"

**Comment by atrayano** [comment]
In CAP.rc you can specify 
MAPL_ENABLE_TIMERS: NO

**Comment by atrayano** [comment]
I take it back - by default the timers are disabled (i.e. unless you specifically ask for MAPL_DISABLE_TIMERS: YES they should not be active). Please check you resource settings

**Comment by tclune** [comment]
@atrayano  First - I'm not sure that switch has any impact on the new timers.   And we really should now delete the old timers.

The barrier's in this thread appear to be in support of timers but are not encapsulated in any way at all.     Not sure who introduced them in CapGridComp - I don't think they were there originally or at least they did not catch my eye at the time I refactored this layer into existence.
