### ISSUE TITLE
Ability to run MAPL with two phases

### ISSUE THREAD

**Issue by WilliamJamieson** [GEOS-ESM/MAPL#743]
@rmontuoro has requested the ability to run both run phases of GOCART independently in the UFS. This is so that the UFS can better emulate how GOCART is run within GEOS. This will require changes to MAPL so that the run method for the MAPL_CapGridComp supports the optional ability to run multiple phases.

Currently, the UFS does not support running multiple phases; however, there is a push on the NOAA side to get the UFS ready to run GOCART in multiple phases. Thus we need to ready MAPL (and GOCART) to support this feature.

**Comment by weiyuan-jiang** [comment]
It seems to me, in GEOS_PhysicsGridCompMod, it already runs two phases of GEOS_ChemGridComp, which runs two phases of GOCART.  What is the eventual order to run the phases of GOCART?

**Comment by WilliamJamieson** [comment]
GOCART in the UFS is run independently of the GEOS_PhysicsGridComp and the GEOS_ChemGridComp (neither of these is used at all).

**Comment by tclune** [comment]
NOAA is not using Physics, nor using Chemistry.       So they cannot drive it indirectly the way it currently happens in GEOS.

**Comment by atrayano** [comment]
@weiyuan-jiang MAPL_CapGridComp should simply run whatever phase the caller wants. The order is determined by the caller, not by MAPL_Cap. Since you asked, the GEOS Physics calls phase 1 of Chem between calls to Surf, and Turb (also phase 1), and then calls phase 2 of Surf, Turb, Chem. But again, this is how GEOS calls Chem. NOAA will decide how they will call it. We just need to make it possible.
