### ISSUE TITLE
Wrong coordinate units provided to the UFS aerosol component

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/MAPL#899]
Both MAPL and GOCART assume that grid coordinates are in radians. However, this may not be the case if the grid is provided externally, as it happens for the UFS aerosol component.

MAPL should check the grid's coordinate system flag and convert the coordinates to radians if needed.

**Comment by tclune** [comment]
@rmontuoro Can you give a more specific scenario?    We are generally aware of this issue, but since we defer regridding to ESMF, that handles most cases where the coordinate system matters.   If an individual component wants to directly access lat/lon  that would be the place that a check should be made.    And I'm sure that GEOS components just assume the radians convention at this point and are thus fragile in that regard.

I'm more than happy to have someone add the necessary hooks if there is a MAPL wrapper layer in use that is pulling this information out of an ESMF grid.   Just want to be certain that this is an actual issue first.

Mentioning @atrayano in case he can think of other cases where we might need this.

**Comment by tclune** [comment]
Ah - I see there is already a PR.   I'll check that - so maybe nothing more is needed here.
