### ISSUE TITLE
HISTORY splitField feature

### ISSUE THREAD

**Issue by gmao-esherman** [GEOS-ESM/MAPL#916]
Variables with a single ungridded dimension are aliased to their original name with 001 appended. For example DUEXTTAU is aliased to DUEXTTAU001. We require the capability to alias a variable with a single ungridded dimension to its original name. Please see HISTORY.rc example below:

'DUEXTTAU'    , 'DU'      , 'DUEXTTAU',

If the above is included in HISTORY.rc it still writes out the varaible to file as "DUEXTTAU001".

**Comment by mathomp4** [comment]
Assigning @bena-nasa, @atrayano and @tclune as...well, they'd know better than I would how to fix this.

**Comment by atrayano** [comment]
This should simple enough to fix quickly. My only concern is that this can be done only if the size of the ungridded dim is 1 (and this is precisely what gmao-esherman needs), otherwise it will be many to one mapping and we cannot distinguish which one is which

**Comment by atrayano** [comment]
@gmao-esherman After taking a closer look at the code, I believe MAPL is working properly. If the alias name is the same as the original field name, the new (split) field has to be named differently since the split field is placed in the same export state as the original field, and we should be able to distinguish them. If you need to produce a split field without "001" string in the name, please try to give it a distinctly different alias name from the original name.

**Comment by atrayano** [comment]
@gmao-esherman If you require this capability, my suggestion would be to change the original name, and use an alias to get the proper output in History. Or a bigger question: why we have a variable with ungridded rank = 1 and size = 1 in a first place? Can we drop the ungridded dims and lower the rank by 1 in the declarations?

**Comment by gmao-esherman** [comment]
@atrayano Thanks for looking into this. The rank of the ungridded dimension for these GOCART2G variables can vary. It depends on how the user sets them. So unfortunately we cannot drop the ungridded dimension.

Your suggestion of changing the variable name in the export state is a good idea and should work. I will have to leave this decision up to @amdasilva and @pcolarco.

**Comment by tclune** [comment]
To be precise here:  it is the _size_ of the ungridded dimension that can vary, not the _rank_.

**Comment by atrayano** [comment]
I agree the size could vary. Nevertheless, the logic in MAPL is: when the resulting new name after the split is the same as the original name, append "split-index", i.e. 001 in this case. Otherwise we will end up with 2 different fields (one has higher rank by 1) with the same name in the same export state

**Comment by pcolarco** [comment]
Hi-

I didn’t catch the origin of the discussion and don’t know how to look up on github.

It sounds like the simplest thing to achieve desired consistency with previous model instances is to rename the export names in DU/NI/SU/SS to something different than e.g., “DUEXTTAU” so that I can alias it to that in HISTORY. This is already practically done for the carbon species as they were renamed from the old BC/OC/BRC style already.

A question about the aliasing in HISTORY: If I create the DUEXTTAU at multiple wavelengths then I get variables like DUEXTTAU001;DUEXTTAU002 in the output that vary from each other sensibly. If I want to alias the name in the file to something more sensible that describes the specific wavelength, like DUEXTTAU470;DUEXTTAU550 this seems not work quite right. I get both variables in my file, but they are filled identically. Is this expected?

Thanks,
Pete


--------------------------------------------------------------------
Peter Colarco
NASA GSFC
Code 614
NASA Goddard Space Flight Center
Greenbelt, MD 20771
301.614.6382 (ph)
301.614.5903 (fax)

***@***.******@***.***>
http://acd-ext.gsfc.nasa.gov/People/Colarco
http://www.researcherid.com/rid/D-8637-2012
--------------------------------------------------------------------


From: Atanas Trayanov ***@***.***>
Reply-To: GEOS-ESM/MAPL ***@***.***>
Date: Friday, July 9, 2021 at 9:17 AM
To: GEOS-ESM/MAPL ***@***.***>
Cc: Peter Colarco ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/MAPL] HISTORY splitField feature (#916)


I agree the size could vary. Nevertheless, the logic in MAPL is: when the resulting new name after the split is the same as the original name, append "split-index", i.e. 001 in this case. Otherwise we will end up with 2 different fields (one has higher rank by 1) with the same name in the same export state

**Comment by atrayano** [comment]
@pcolarco No, this is not expected. Aliasing should affect only the naming of the output variables. Thanks for reporting it. The values should have been identical to the output when the variables were named DUEXTTAU001;DUEXTTAU002 . I'll take a closer look

**Comment by pcolarco** [comment]
Hi Atanas-
Thank you, I hope I described that well enough.

Pete



--------------------------------------------------------------------
Peter Colarco
NASA GSFC
Code 614
NASA Goddard Space Flight Center
Greenbelt, MD 20771
301.614.6382 (ph)
301.614.5903 (fax)

***@***.******@***.***>
http://acd-ext.gsfc.nasa.gov/People/Colarco
http://www.researcherid.com/rid/D-8637-2012
--------------------------------------------------------------------


From: Atanas Trayanov ***@***.***>
Reply-To: GEOS-ESM/MAPL ***@***.***>
Date: Friday, July 9, 2021 at 12:43 PM
To: GEOS-ESM/MAPL ***@***.***>
Cc: Peter Colarco ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/MAPL] HISTORY splitField feature (#916)


@pcolarco<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpcolarco&data=04%7C01%7Cpeter.r.colarco%40nasa.gov%7C78d7adcb96cf4a7bfa2808d942f87a9f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637614458003318476%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HgpcgcCTEucaZF2RIB%2BYof8QTfr4uUEoro9Wg%2BfkCh4%3D&reserved=0> No, this is not expected. Aliasing should affect only the naming of the output variables. Thanks for reporting it. The values should have been identical to the output when the variables were named DUEXTTAU001;DUEXTTAU002 . I'll take a closer look

**Comment by atrayano** [comment]
@pcolarco Hi Pete, I tried to reproduce the behavior you had described, but in my much simpler experiment I was getting the results I was expecting, i.e. regardless of the aliasing, differently named fields had different values. It will be very helpful, if you could point me to your experiment, as well as to your source code sandbox, hopefully on discover. I want to check which version of MAPL you are using as well as to borrow your setup to reproduce the issue myself

**Comment by pcolarco** [comment]
I apologize @atrayano I tried it again just now and it works. I must have been confusing things with the other issues Elliot and I were working on. Sorry for the traffic.
